### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [1]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [5]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [6]:
# with reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [7]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
# np.random
np.random.random((3,4))

array([[0.60611851, 0.30211003, 0.98088931, 0.65429434],
       [0.84608423, 0.58580683, 0.70675424, 0.28270766],
       [0.57981921, 0.52021277, 0.37385464, 0.62876679]])

In [10]:
# np.linspace
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [11]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [12]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [13]:
# ndim
a3.ndim

3

In [14]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [16]:
# itemsize
a3.itemsize

8

In [17]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int32
float64
int64


### Changing Datatype

In [18]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [66]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print(a2)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [68]:
# scalar operations

# arithmetic
a1 *3

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [71]:
# relational  >5 print true and lessthan print false
a1>5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [72]:
# vector operations (applied on two numpy arrays)
# arithmetic
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

### Array Functions

In [74]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[33., 22., 89.],
       [65., 96., 18.],
       [22., 41., 31.]])

In [76]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.max(a1,axis=1)

array([89., 96., 41.])

In [78]:
# mean/median/std/var
np.median(a1,axis=1)

array([33., 65., 31.])

In [26]:
# trigonomoetric functions
np.sin(a1)

array([[ 0.82682868,  0.29636858,  0.99060736],
       [ 0.27090579,  0.1673557 ,  0.86006941],
       [ 0.37960774, -0.92345845, -0.75098725]])

In [27]:
# dot product multpilying two matrices simply
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [28]:
# log and exponents
np.exp(a1)

array([[1.69488924e+28, 3.18559318e+16, 1.20260428e+06],
       [1.44625706e+12, 2.29378316e+27, 4.48961282e+38],
       [1.33833472e+42, 2.23524660e+37, 6.56599691e+07]])

In [29]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[42., 24., 29.],
       [66., 75., 79.]])

### Indexing and Slicing

In [30]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [31]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
a2[1,0]

np.int64(4)

In [34]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [35]:
a3[1,0,1]

np.int64(5)

In [36]:
a3[1,1,0]

np.int64(6)

In [37]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a1[2:5:2]

array([2, 4])

In [39]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [41]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [42]:
a2[1,::3]

array([4, 7])

In [43]:
a2[0,:]

array([0, 1, 2, 3])

In [44]:
a2[:,2]

array([ 2,  6, 10])

In [45]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [46]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [47]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [48]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [49]:
a3[0,1,:]

array([3, 4, 5])

### Iterating

In [50]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [51]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [53]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [54]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [55]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [79]:
# reshape
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [80]:
# Transpose (it changes row into col and col into row)
np.transpose(a2)


array([[12, 16, 20],
       [13, 17, 21],
       [14, 18, 22],
       [15, 19, 23]])

In [81]:
# ravel (whatever the dimension of array it will convert into an 1D array)
a2.ravel()

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

### Stacking

In [59]:
#stacking means combining multiple arrays into a single array
# horizontal stacking(stacks arrays column-wise)
# horizontal stacking(stacks arrays row-wise)
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [82]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.hstack((a, b))
print(result)

[1 2 3 4 5 6]


In [60]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [83]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.vstack((a, b))
print(result)

[[1 2 3]
 [4 5 6]]


In [61]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

Splitting means dividing one array into multiple smaller arrays.

In [84]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

result = np.split(arr, 3)

print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [85]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [93]:
# vertical splitting
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [ ]:
a5

In [ ]:
np.vsplit(a5,2)